### ISSUE TITLE
Hello, i paste the link into my TiviMax (apple tv) but none is working. Tried on VLC, all is working fine. Is there anything i missed? 

### ISSUE THREAD

**Issue by faizalkamaruddin** [weareblahs/freeview#13]

**Comment by weareblahs** [comment]
Seems like the app you used doesn't support MPD manifests (used from RTMklik streams for RTM channels). VLC does support this format.

**Comment by faizalkamaruddin** [comment]
Thank you. Ive used the m3u editor and reorganize the link to be used with my xtream code. Now it works and i can watch on my apple tv. Kudos bro
