### ISSUE TITLE
All Channels Error

### ISSUE THREAD

**Issue by stevenpandey** [weareblahs/freeview#14]
Hi mate, all channels error. Would you please fix it? Thank you!

**Comment by weareblahs** [comment]
All channels are now currently accessible in Malaysia. If the problem still persists, please check if you have your VPN turned on or not.

Most of the channels in this playlist is provided from its original web stream, so it's geo blocked to Malaysia. You can try using TiviMate to play it if you're in Malaysia and you can't watch the channels.
