### ISSUE TITLE
Video delay on rtm channel

### ISSUE THREAD

**Issue by sahalsaad** [weareblahs/freeview#24]
Hi, 

The video will be delayed on any rtm's channels.
It will be delayed when it renders high-quality video.
If just after selecting the channel and still rendering low-quality video, there is no sync issue. It only happens after the video start to become a high-quality video. Do you know how to fix this? Thank you.

**Comment by weareblahs** [comment]
Not sure why. Probably an issue with your internet or there's an issue with RTM's own servers.

Do note that I didn't manage the links. You can also test the speed via RTM Klik, which is the same source for RTM channels for this playlist.

**Comment by sahalsaad** [comment]
Force to render high res fixed the issue. No more delay. Thanks.
