### ISSUE TITLE
live-xtra-sg1.global.ssl.fastly.net stopped working

### ISSUE THREAD

**Issue by sahalsaad** [weareblahs/freeview#28]
In Postman the referer must be `https://live-xtra-sg1.global.ssl.fastly.net/embed/index.html`

I try to update it, but it still does not work. Any idea?

**Comment by PRSXFENG** [comment]
seems to work fine for me in kodi

**Comment by sahalsaad** [comment]
does that mean this list only for kodi ?

**Comment by PRSXFENG** [comment]
I got no clue tbh, what client are you using?

**Comment by sahalsaad** [comment]
I'm trying with VLC and [m3u iptv](https://play.google.com/store/apps/details?id=de.herber_edevelopment.m3uiptv)

It was working fine previously. Just stop working last week.

**Comment by samleong123** [comment]
live-xtra-sg1.global.ssl.fastly.net is deprecated from Media Prima side
