### ISSUE TITLE
Tonton channel was not available on freeview

### ISSUE THREAD

**Issue by leesai254** [weareblahs/freeview#35]
I checked the tonton channel like tv3 was not available anymore. Can someone solve this problem

**Comment by weareblahs** [comment]
Updated. Please check.

**Comment by leesai254** [comment]
Hi weareblahs, i have checked , still show unavailable and An error
occurred: code 403

Tan Yu Xuan ***@***.***> 于2023年10月15日周日 22:04写道：

**Comment by weareblahs** [comment]
Not sure what's the issue. At my side, it works properly.

Do note that all links in this playlist are sourced from official websites, for Media Prima channels, the link is sourced from https://www.xtra.com.my/live-tv/. Try deleting and adding the playlist again. If the problem persists, the only remaining way is to watch it through the website above or cast it.

**Comment by leesai254** [comment]
OK Noted and thank you

**Comment by mohdrajib** [comment]
> Not sure what's the issue. At my side, it works properly.
> 
> Do note that all links in this playlist are sourced from official websites, for Media Prima channels, the link is sourced from https://www.xtra.com.my/live-tv/. Try deleting and adding the playlist again. If the problem persists, the only remaining way is to watch it through the website above or cast it.

hi.. can share your app.. name/version,. when you tested and works properly.. i use tivimate / 4.7.0

**Comment by weareblahs** [comment]
> > Not sure what's the issue. At my side, it works properly.
> > 
> > Do note that all links in this playlist are sourced from official websites, for Media Prima channels, the link is sourced from https://www.xtra.com.my/live-tv/. Try deleting and adding the playlist again. If the problem persists, the only remaining way is to watch it through the website above or cast it.
> 
> hi.. can share your app.. name/version,. when you tested and works properly.. i use tivimate / 4.7.0 
> 

I'm using TVirl for TV stuff since it integrates with the Live Channels app on Android TV. If you still can't use, then you can try installing Tonton on Android TV devices.
