### ISSUE TITLE
tv3 not working, is this only happens on my end? 

### ISSUE THREAD

**Issue by mrnoobnoobies** [weareblahs/freeview#7]
tv1 and tv2 is working. how about tv3? how to make this working? tq

**Comment by Kendo09** [comment]
Tv3, tv8 and tv9 are not working, please help, I have emailed and telegram the author to help

**Comment by weareblahs** [comment]
Not sure why, but these links isn't managed by others - temporary solution is to use https://www.xtra.com.my/live-tv/ to watch. If this is fixed (temporary or permanent), I'll notify you - this may take some time.

**Comment by weareblahs** [comment]
See https://github.com/samleong123/tonton_dailymotion_php/issues/10#issuecomment-1288040891.

**Comment by samleong123** [comment]
Solution : Use your own devices with Docker and run the container with my image 
Details here : [https://github.com/samleong123/mediaprima_dailymotion_docker](https://github.com/samleong123/mediaprima_dailymotion_docker)

This repo will be archived and become deprecated , please refer to this [new](https://github.com/samleong123/mediaprima_dailymotion_docker) repo that uses Docker

**Comment by samleong123** [comment]
Solution : Use your own devices with Docker and run the container with my image for Media Prima channels
Details here : [https://github.com/samleong123/mediaprima_dailymotion_docker](https://github.com/samleong123/mediaprima_dailymotion_docker)

[This](https://github.com/samleong123/tonton_dailymotion_php) repo will be archived and become deprecated , please refer to this [new](https://github.com/samleong123/mediaprima_dailymotion_docker) repo that uses Docker
